nodeLinker: node-modules

npmPublishAccess: restricted

npmScopes:
  getsaas:
    npmAuthToken: "${GH_PAT}"
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
